/* V-RIDE VENEZUELA — Migración 005
   Adapta los 5 módulos de capacitación al contexto venezolano
   Cambios por módulo:
   1 — modelo de pago: membresía semanal + cobro directo al pasajero
   2 — descripción de pasajeros: contexto venezolano general
   3 — accidente: cita LTT 2008 Art. 86, autoridades INTT / PTT
   4 — LOPCD: G.O. N° 38.598, 2007; elimina "caballo miniatura"
   5 — seguro: cita LTT 2008 Arts. 58 y 192, elimina monto USA;
       modelo de negocio: 100% al conductor + membresía semanal
*/

/* ═══════════════════════════════════════════════════════════════
   MÓDULO 1 — Navegación de la Plataforma y la App del Conductor
   ═══════════════════════════════════════════════════════════════ */
UPDATE training_modules SET
  content = '[
    {"title":"Primeros Pasos","body":"Descarga la app V-Ride Conductor desde la App Store (iOS) o Google Play (Android). Busca ''V-Ride Conductor'' — asegúrate de descargar la app de Conductor, no la de Pasajero.\n\nPara iniciar sesión: abre la app → toca Iniciar Sesión → ingresa tu correo electrónico y contraseña registrados. Si olvidaste tu contraseña, toca ''Olvidé mi Contraseña'' — el enlace de restablecimiento llega en un plazo de 2 minutos."},
    {"title":"Resumen del Panel del Conductor","body":"Elementos principales de la pantalla:\n• Botón Conectarse / Desconectarse — activa o desactiva tu disponibilidad\n• Vista de mapa — muestra tu ubicación y la actividad cercana\n• Resumen de viajes — número de viajes del día y valor estimado acumulado\n• Ventana emergente de solicitud de viaje — aparece cuando un pasajero coincide contigo (tienes 30 segundos para aceptar)\n• Barra de navegación (inferior) — Inicio, Viajes, Ganancias, Cuenta, Ayuda\n• Indicador de estado — Verde = conectado. Gris = desconectado.\n\nPara conectarte: asegúrate de que tu vehículo esté limpio → abre la app → toca el botón grande Conectarse → el indicador de estado se pone verde."},
    {"title":"Recepción y Aceptación de Solicitudes de Viaje","body":"Cuando un pasajero solicita un viaje cerca de ti, aparece una ventana emergente. Tienes 30 segundos para aceptar o rechazar. La solicitud muestra: nombre y calificación del pasajero, ubicación de recogida y distancia, duración y distancia del viaje, tipo de vehículo y tarifa estimada.\n\nCómo aceptar un viaje:\n1. Toca Aceptar dentro de los 30 segundos\n2. Sigue el GPS hasta el punto de recogida\n3. Toca ''He Llegado'' al llegar al punto de recogida\n4. Espera hasta 5 minutos al pasajero\n5. Toca ''Iniciar Viaje'' una vez que el pasajero esté a bordo\n6. Sigue el GPS hasta el destino\n7. Toca ''Finalizar Viaje'' al llegar\n\nIMPORTANTE: Confirma siempre el nombre del pasajero antes de iniciar el viaje."},
    {"title":"Durante el Viaje","body":"Navegación: la app utiliza Google Maps para las indicaciones de ruta. No te desvíes de la ruta sugerida sin el acuerdo del pasajero. Si es necesario un desvío por tráfico, informa primero al pasajero. Nunca uses el teléfono con las manos — usa siempre un soporte para el tablero.\n\nComunicación dentro de la app: toca el ícono de teléfono para llamar a través de la app (el número queda oculto). Toca el ícono de mensaje para enviar textos predefinidos. Nunca compartas tu número de teléfono personal con los pasajeros."},
    {"title":"Ganancias y Membresía","body":"MODELO DE PAGO EN V-RIDE VENEZUELA\nLos pasajeros te pagan DIRECTAMENTE a ti por cada viaje completado. V-Ride no intermedia en el cobro entre conductor y pasajero. El monto se acuerda según la tarifa establecida. Métodos de cobro más comunes: efectivo (bolívares o dólares), Pago Móvil, transferencia bancaria.\n\nMEMBRESÍA SEMANAL\nPara operar en la plataforma pagas una membresía semanal a V-Ride según tu tipo de vehículo:\n• Motocicleta: $15 USD por semana\n• Sedán: $25 USD por semana\n• SUV: $30 USD por semana\n\nEl pago vence cada viernes. Métodos aceptados: Zelle, Binance Pay, PayPal, Pago Móvil o transferencia bancaria. Envía el comprobante a través de la app para verificación. Tu acceso permanece activo mientras tu membresía esté vigente.\n\nHISTORIAL DE VIAJES\nToca Ganancias en la barra de navegación inferior para consultar tus viajes completados por día, semana o mes y el valor estimado acumulado."},
    {"title":"Funciones de Emergencia y Seguridad","body":"Botón SOS: ubicado en la esquina superior derecha de tu pantalla durante cualquier viaje activo. Al tocarlo, se llama de inmediato al 911, se alerta al Soporte de V-Ride con tu ubicación GPS y se comparte tu ubicación en tiempo real con los servicios de emergencia. Usa el botón SOS únicamente para emergencias reales — las activaciones falsas violan el Acuerdo de Conductor.\n\nChat de soporte dentro de la app: toca Ayuda en la barra de navegación inferior. El soporte por chat está disponible las 24 horas, los 7 días de la semana. Para asuntos no urgentes usa el chat — para emergencias usa el SOS o llama al 911."}
  ]',
  updated_at = NOW()
WHERE code = 'VRN-TRN-021';

/* ═══════════════════════════════════════════════════════════════
   MÓDULO 2 — Excelencia en el Servicio al Cliente
   ═══════════════════════════════════════════════════════════════ */
UPDATE training_modules SET
  content = '[
    {"title":"Conoce a tus Pasajeros","body":"Los pasajeros de V-Ride Venezuela son ciudadanos que buscan transporte seguro, cómodo y puntual en su ciudad. Pueden ser:\n• Trabajadores y profesionales que necesitan llegar a tiempo a sus destinos\n• Estudiantes de universidades, institutos y bachillerato\n• Adultos mayores que prefieren no conducir o no tienen vehículo propio\n• Personas con condiciones de movilidad reducida o discapacidad\n• Pacientes que viajan hacia y desde citas médicas o centros de salud\n• Familias que necesitan transporte de confianza\n• Cualquier persona que prefiera una alternativa segura y cómoda al transporte público o el taxi informal\n\nV-Ride Venezuela nació para ofrecer una opción de transporte digna y confiable. La seguridad y el profesionalismo que ofreces son la razón por la que los pasajeros nos eligen. Tu comportamiento construye la reputación de toda la plataforma."},
    {"title":"El Estándar de Servicio V-Ride — 5 Compromisos","body":"1. PUNTUAL — Llega a tiempo. Si te retrasas, avisa de inmediato a través de la app.\n2. PROFESIONAL — Vehículo limpio, apariencia cuidada, tono respetuoso en todo momento.\n3. PACIENTE — Nunca apresures a tu pasajero. Dale todo el tiempo que necesite.\n4. PROACTIVO — Ofrece ayuda antes de que te la pidan. Abre puertas, ofrece tu brazo si aplica, ayuda con el equipaje.\n5. PRESENTE — Dedica toda tu atención a la seguridad y comodidad del pasajero durante todo el viaje."},
    {"title":"Llegada y Abordaje","body":"Al llegar:\n• Estaciona lo más cerca posible de la entrada del punto de recogida, siempre que sea seguro\n• Baja del vehículo — NO toques la bocina ni esperes dentro del carro\n• Saluda al pasajero por su nombre: ''Hola, ¿es usted [Nombre]? Soy [Tu Nombre], de V-Ride.''\n• Ofrece ayuda con el equipaje o dispositivo de movilidad si lo tiene\n• Abre la puerta del pasajero\n• Si parece necesitar ayuda para llegar al vehículo, pregunta primero: ''¿Le ayudo a llegar al carro?''\n• Espera pacientemente hasta que esté completamente sentado y cómodo antes de cerrar la puerta\n\nAyuda con dispositivos de movilidad: pregunta siempre antes de tocar una silla de ruedas, andador o bastón. NUNCA intentes levantar físicamente a un pasajero — ayuda solo con el equilibrio y el apoyo."},
    {"title":"Durante el Viaje","body":"Conversación: saluda con calidez y pregunta si la temperatura es agradable. Deja que el pasajero marque la pauta — algunos prefieren silencio, otros disfrutan conversar. Nunca discutas temas de religión, política o temas controversiales. Si comparten preocupaciones personales o de salud, escucha con empatía — no des consejos.\n\nConducción para su comodidad: acelera y frena de forma gradual — los movimientos bruscos generan incomodidad. Evita baches y vías en mal estado cuando sea posible. Mantén la música apagada o muy baja, a menos que te la pidan. Nunca uses el teléfono mientras conduces."},
    {"title":"Situaciones Difíciles","body":"Pasajero confundido sobre el destino: confirma con calma — ''Quiero asegurarme de llevarlo al lugar correcto. La dirección en la app indica [dirección]. ¿Es correcto?'' Si tienes dudas, llama a soporte antes de partir.\n\nPasajero se altera: reconoce la situación con calma — ''Veo que está pasando un momento difícil. Tómese su tiempo — estoy aquí para llevarlo de forma segura.'' Conduce con suavidad y en silencio.\n\nPasajero se mueve lentamente: el pasajero que tienes enfrente es tu ÚNICA prioridad. Nunca lo apresures.\n\nPasajero es grosero o agresivo: mantén la calma, no confrontes. Si la situación es grave, detente en un lugar seguro. Usa el SOS si hay amenazas. Reporta el incidente inmediatamente después del viaje."},
    {"title":"Calificaciones y Comentarios","body":"Tu calificación como conductor es la métrica más importante de la plataforma. Los conductores por debajo de 4,5 estrellas reciben advertencias. Calificaciones sostenidas por debajo de 4,5 pueden resultar en la desactivación de la cuenta.\n\nLa Lista de Verificación de 5 Estrellas:\n✓ Llega a tiempo o antes\n✓ Baja del vehículo y saluda al pasajero por su nombre\n✓ Ofrece ayuda antes de que te la pidan\n✓ Conduce con suavidad — sin frenazos bruscos\n✓ Mantén el vehículo limpio y a una temperatura agradable\n✓ Sé cálido, paciente y profesional en todo momento"}
  ]',
  updated_at = NOW()
WHERE code = 'VRN-TRN-022';

/* ═══════════════════════════════════════════════════════════════
   MÓDULO 3 — Protocolos de Seguridad y Procedimientos de Emergencia
   ═══════════════════════════════════════════════════════════════ */
UPDATE training_modules SET
  content = '[
    {"title":"Lista de Verificación de Seguridad Antes del Viaje","body":"Antes de conectarte cada día, completa esta verificación:\n• Todas las luces exteriores — deben funcionar correctamente\n• Neumáticos — con presión adecuada, sin daños\n• Cinturones de seguridad — todos retráctiles y con seguro\n• Luces de advertencia del tablero — ninguna encendida\n• Limpieza interior — limpio y sin olores\n• Carga del teléfono — por encima del 50% (cárgalo si está por debajo del 20% antes de conducir)\n• Soporte del teléfono — soporte fijo en el tablero o parabrisas\n• Condición personal — descansado, alerta y sobrio\n\nTOLERANCIA CERO: V-Ride tiene una política de tolerancia cero para conducir bajo los efectos del alcohol, drogas o cualquier medicamento que altere la capacidad de conducir. Su incumplimiento resulta en la desactivación permanente e inmediata."},
    {"title":"Estándares de Conducción Segura","body":"En la vía:\n• Respeta siempre los límites de velocidad indicados — sin excepciones\n• Detente por completo en todas las señales de PARE y semáforos en rojo\n• Nunca uses el teléfono con las manos mientras conduces\n• Mantén una distancia de seguimiento segura con el vehículo de adelante\n• Usa las luces direccionales en cada cambio de canal y giro\n• Nunca conduzcas de forma agresiva — sin pegarte al carro de adelante ni cerrar el paso\n\nPara la seguridad del pasajero:\n• Acelera y frena de forma gradual — siempre\n• Evita baches y vías en mal estado cuando sea posible\n• No hagas giros bruscos — solo giros amplios y suaves\n• Espera hasta que el pasajero esté completamente sentado y con el cinturón puesto antes de avanzar\n• NUNCA muevas el vehículo si un pasajero está de pie o no está asegurado"},
    {"title":"Respuesta ante un Accidente de Tránsito","body":"Pasos inmediatos (LTT 2008, Art. 86):\n1. DETENTE de inmediato — no te retires del lugar bajo ninguna circunstancia\n2. Enciende las luces de emergencia\n3. Verifica si tú o tu pasajero tienen lesiones\n4. Llama al 911 si hay algún herido — indica tu ubicación con claridad\n5. Si no hay heridos y el vehículo puede circular, muévete hacia el lado de la vía\n6. NO admitas responsabilidad ni discutas sobre quién tuvo la culpa\n7. Intercambia datos: nombre, cédula, placa y aseguradora con los demás involucrados\n8. Fotografía los daños del vehículo, la escena y las condiciones de la vía\n9. Reporta el incidente de inmediato a través de la app V-Ride\n10. Levanta un acta ante la Policía de Tránsito Terrestre (PTT) o el INTT si hay heridos o disputa\n\nDarse a la fuga en caso de accidente está sancionado con multa de 10 U.T. y puede acarrear responsabilidad penal (LTT 2008, Art. 169.23).\n\nDespués de un accidente: mantén la calma. Pregunta al pasajero ''¿Está usted bien? ¿Siente algún dolor?'' NO muevas al pasajero si reporta dolor en el cuello o la espalda — espera a los servicios de emergencia."},
    {"title":"Emergencia Médica del Pasajero","body":"Señales de una emergencia médica:\n• Falta de respuesta o pérdida súbita de conciencia\n• Dolor en el pecho o dificultad para respirar\n• Dolor de cabeza súbito y severo, o confusión repentina\n• Convulsiones o temblores incontrolables\n• Señales de accidente cerebrovascular: caída facial, debilidad en el brazo, dificultad para hablar\n• Reacción alérgica grave: hinchazón, dificultad para respirar\n\nPasos a seguir:\n1. Detente de forma segura e inmediata — enciende las luces de emergencia\n2. Llama al 911 — describe los síntomas con claridad\n3. Indica al operador tu ubicación GPS exacta desde la app\n4. Usa el botón SOS de la app para alertar al Soporte de V-Ride\n5. Permanece en línea con el 911 y sigue las instrucciones\n6. NO dejes solo al pasajero\n7. Si el operador te lo indica — inicia RCP\n8. Desbloquea las puertas del vehículo para que los servicios de emergencia puedan acceder\n\nNO lleves al pasajero al hospital por tu cuenta — llama al 911 y espera a los servicios de emergencia."},
    {"title":"Amenazas a la Seguridad y Condiciones Climáticas","body":"Si te sientes inseguro: mantén la calma, no confrontes. Dirígete a un lugar público, una estación de bomberos o una comandancia policial. Usa el SOS de la app si estás en peligro inmediato. Al detenerte en un lugar seguro, pide al pasajero que baje con calma.\n\nSituaciones de tolerancia cero (detente, pide al pasajero que baje, usa el SOS, reporta de inmediato):\n• El pasajero está intoxicado y se comporta de forma agresiva\n• El pasajero hace comentarios de índole sexual o intenta contacto físico\n• El pasajero te amenaza con algún arma\n• El pasajero te pide desviarte hacia un lugar no verificado\n\nLluvias y vías inundadas (especialmente mayo–octubre en Venezuela):\n• Nunca conduzcas a través de vías inundadas — da la vuelta siempre, nunca arriesgues tu vida ni la de tus pasajeros\n• Reduce la velocidad considerablemente con lluvia intensa — la visibilidad y el agarre disminuyen\n• Ante tormenta eléctrica, resguárdate en una edificación sólida — NUNCA debajo de un puente\n• Sigue todas las alertas de pausa de la plataforma que aparezcan en la app"}
  ]',
  updated_at = NOW()
WHERE code = 'VRN-TRN-023';

/* ═══════════════════════════════════════════════════════════════
   MÓDULO 4 — Cumplimiento de la LOPCD y Sensibilización
   ═══════════════════════════════════════════════════════════════ */
UPDATE training_modules SET
  content = '[
    {"title":"La LOPCD y tus Responsabilidades","body":"La Ley para Personas con Discapacidad de Venezuela (LOPCD, G.O. N° 38.598, 26/01/2007) es una ley nacional que protege los derechos de las personas con discapacidad y prohíbe la discriminación en todos los ámbitos de la vida pública — incluido el transporte.\n\nComo conductor de V-Ride, NO PUEDES:\n• Negar el servicio a un pasajero por causa de una discapacidad\n• Negar el servicio a un pasajero que viaje con un perro de asistencia debidamente entrenado\n• Cobrar un monto adicional por necesidades de accesibilidad\n• Tratar a un pasajero con discapacidad con menos dignidad que a cualquier otro pasajero\n\nCualquier conductor que se determine que negó el servicio por causa de una discapacidad será desactivado de forma inmediata y permanente. V-Ride Venezuela colaborará con cualquier investigación relacionada con una denuncia de este tipo."},
    {"title":"Lenguaje que Prioriza a la Persona","body":"El lenguaje que prioriza a la persona coloca a la persona antes que su discapacidad. Reconoce que una discapacidad es solo una parte de la persona — no su identidad.\n\nDi esto → No esto:\n• ''Persona con discapacidad'' → ''Discapacitado'' / ''los discapacitados''\n• ''Persona que usa silla de ruedas'' → ''Postrado en silla de ruedas'' / ''confinado a una silla de ruedas''\n• ''Persona con discapacidad visual'' → ''Ciego'' / ''los ciegos''\n• ''Persona con discapacidad auditiva'' → ''Sordomudo'' / ''los sordos''\n• ''Persona con discapacidad cognitiva'' → ''Retrasado mental'' / ''lento''\n• ''Persona con demencia'' → ''Demente'' / ''senil''\n\nEn caso de duda: trata a cada pasajero como quisieras que trataran a un familiar tuyo."},
    {"title":"Perros de Asistencia","body":"Conforme a la LOPCD (G.O. N° 38.598, 2007), un perro de asistencia es un animal entrenado específicamente para realizar una tarea determinada en beneficio de una persona con discapacidad.\n\nSOLO puedes hacer DOS preguntas:\n1. ¿Este animal es requerido debido a una discapacidad?\n2. ¿Qué trabajo o tarea ha sido entrenado para realizar?\n\nNO PUEDES:\n• Preguntar sobre la naturaleza o gravedad de la discapacidad del pasajero\n• Pedir documentación, credenciales o comprobante de entrenamiento del animal\n• Negar el servicio por tus propias alergias al animal\n• Negar el servicio porque otro pasajero sea alérgico\n• Exigir que el perro de asistencia viaje en el maletero o área de carga\n\nLos animales de compañía sin función de asistencia no están cubiertos por la LOPCD, pero la política de V-Ride es aceptar a todos los animales que viajen de forma tranquila y no representen un riesgo. En caso de duda, acepta el viaje y reporta cualquier inquietud a Soporte después."},
    {"title":"Pasajeros con Silla de Ruedas y Dispositivos de Movilidad","body":"Pautas generales:\n• Pregunta siempre antes de tocar la silla de ruedas o cualquier dispositivo de movilidad\n• Pregunta al pasajero cómo prefiere que lo ayudes — nunca asumas\n• Nunca empujes una silla de ruedas manual sin permiso\n• Pliega andadores y bastones y colócalos en el maletero o asiento trasero según prefiera el pasajero\n\nAseguramiento de la silla de ruedas (vehículos accesibles — sistema de 4 puntos):\n1. Coloca la silla de ruedas mirando hacia adelante en el área de aseguramiento\n2. Coloca los amarres delanteros — izquierdo y derecho — en ángulo de 45 grados\n3. Coloca los amarres traseros — izquierdo y derecho — en ángulo de 45 grados\n4. Verifica que los cuatro amarres estén firmes — sin holgura\n5. Abrocha el cinturón de cadera sobre el regazo del pasajero\n6. Abrocha el cinturón de hombro sobre el pecho del pasajero\n7. Pregunta: ''¿Está cómodo y seguro?''\n8. No comiences a conducir hasta que el pasajero confirme que está listo"},
    {"title":"Cómo Comunicarte con Pasajeros con Discapacidad","body":"Pasajeros con discapacidad auditiva:\n• Mira al pasajero al hablar — muchos leen los labios\n• Habla con claridad y a volumen normal — no grites\n• Usa la mensajería de la app para comunicación escrita si resulta útil\n• Confirma el destino por escrito si existe alguna duda\n\nPasajeros con discapacidad visual:\n• Preséntate por tu nombre al acercarte: ''Hola, soy [Nombre], de V-Ride''\n• Ofrece tu brazo — no tomes al pasajero por sorpresa\n• Describe el camino hacia el vehículo: ''La puerta del carro está a unos tres pasos a su derecha''\n• Avísale cuando llegues al destino\n\nPasajeros con dificultades cognitivas o de memoria:\n• Habla despacio y con claridad — usa oraciones cortas\n• Confirma el destino antes y durante el viaje si hay incertidumbre\n• Ten paciencia con las preguntas repetitivas — nunca muestres frustración\n• Si un pasajero parece confundido y en riesgo, contacta al Soporte de V-Ride antes de finalizar el viaje"}
  ]',
  updated_at = NOW()
WHERE code = 'VRN-TRN-024';

/* ═══════════════════════════════════════════════════════════════
   MÓDULO 5 — Normativa de Tránsito y Regulaciones Venezuela
   ═══════════════════════════════════════════════════════════════ */
UPDATE training_modules SET
  content = '[
    {"title":"Normativa de Tránsito en Venezuela — Reglas Clave","body":"CONDUCCIÓN CON MANOS LIBRES\nSegún la Ley de Transporte Terrestre (LTT 2008, Art. 169.12), está prohibido usar un dispositivo de comunicación mientras conduces sin dispositivo de manos libres — incluso en un semáforo en rojo. Sanción: 10 U.T. La política de V-Ride va más allá: tu teléfono debe estar siempre montado en un soporte. El uso del teléfono en la mano es motivo de desactivación.\n\nLÍMITES DE VELOCIDAD (referencia)\n• Zona escolar en horario activo: 30 km/h\n• Calles residenciales: 40–50 km/h (salvo indicación contraria)\n• Autopistas urbanas: 80–100 km/h (según lo indicado)\n• Carreteras nacionales: 100–120 km/h (según lo indicado)\nExceso de velocidad: multa de 10 U.T. (LTT 2008, Art. 169.4)\n\nCINTURÓN DE SEGURIDAD\nTodos los ocupantes deben usar el cinturón. Eres responsable de verificar que tu pasajero esté abrochado antes de partir. (LTT 2008, Art. 73.5)\n\nCESIÓN DE PASO A VEHÍCULOS DE EMERGENCIA\nDebes cambiarte de canal o reducir considerablemente la velocidad al pasar junto a vehículos del INTT, PTT, Bomberos o ambulancias con las luces encendidas.\n\nCERO ALCOHOL Y DROGAS\nConducir bajo los efectos del alcohol o drogas: multa de 10 U.T. más suspensión de licencia, y el conductor se presume responsable de cualquier accidente ocurrido bajo ese estado. (LTT 2008, Art. 169.8 y Art. 194)\n\nVÍAS INUNDADAS\nNunca cruces una vía inundada. Durante la temporada de lluvias (mayo–octubre) las inundaciones pueden ser repentinas y peligrosas. Da la vuelta siempre."},
    {"title":"Regulaciones para V-Ride Venezuela","body":"V-Ride Venezuela es una plataforma tecnológica de transporte privado que conecta a pasajeros con conductores independientes, bajo la supervisión del Instituto Nacional de Transporte Terrestre (INTT) y en cumplimiento con la Ley de Transporte Terrestre 2008.\n\nREQUISITOS PARA CONDUCTORES\n• Licencia de conducir vigente del grado correspondiente al vehículo — verificada en la afiliación y revisada anualmente\n• Verificación de antecedentes — previa a la activación y revisada anualmente\n• Sin antecedentes de conducción bajo los efectos del alcohol en los últimos 7 años\n• Sin delitos graves en los últimos 7 años\n• Edad mínima: 18 años según LTT 2008 — V-Ride establece un estándar más alto de 21 años\n• Vehículo con revisión técnica vigente y seguro de responsabilidad civil vigente\n\nPOLÍTICA DE TOLERANCIA CERO\nV-Ride suspende de inmediato a cualquier conductor que reciba una denuncia de tolerancia cero, investiga en 24 horas y reincorpora solo tras verificar resultado negativo en la prueba correspondiente."},
    {"title":"Seguro de Responsabilidad Civil","body":"OBLIGATORIO POR LEY\nTodo vehículo a motor debe estar amparado por una póliza de seguro de responsabilidad civil vigente para responder por los daños causados a terceros. Para motocicletas rige en las mismas condiciones que para los automotores. (LTT 2008, Art. 58)\n\nCircular sin póliza de seguro vigente está sancionado con multa de 5 U.T. (LTT 2008, Art. 170.3). V-Ride exige que tu póliza esté vigente en todo momento como requisito para operar en la plataforma.\n\nRESPONSABILIDAD EN CASO DE ACCIDENTE\nEl conductor, el propietario del vehículo y su aseguradora son solidariamente responsables de los daños causados a terceros. (LTT 2008, Art. 192)\n\nFase 1 — App APAGADA: solo tu seguro personal de responsabilidad civil aplica.\nFase 2 — App ENCENDIDA, sin viaje: tu póliza vigente cubre tu actividad.\nFase 3 — Viaje activo: tu póliza cubre el servicio prestado al pasajero.\n\nIMPORTANTE: Verifica con tu aseguradora que tu póliza cubre el transporte de pasajeros con fines comerciales. Algunas pólizas de uso personal excluyen el transporte remunerado."},
    {"title":"Modelo de Negocio y tus Derechos","body":"CÓMO FUNCIONA V-RIDE VENEZUELA\nComo conductor afiliado a V-Ride, no eres empleado — eres un contratista independiente que opera bajo el modelo de membresía semanal.\n\n• Pagas una membresía semanal a V-Ride según tu tipo de vehículo:\n  - Motocicleta: $15 USD por semana\n  - Sedán: $25 USD por semana\n  - SUV: $30 USD por semana\n• El 100% de lo que cobras en cada viaje es tuyo — V-Ride no descuenta comisión por viaje.\n• Los pasajeros te pagan directamente (efectivo, Pago Móvil, transferencia u otro método acordado).\n• La plataforma gestiona la conexión conductor–pasajero, el GPS del viaje y el sistema de calificaciones.\n\nTUS DERECHOS\n• Establecer tu propio horario — sin mínimo de horas exigido.\n• Trabajar para otras plataformas simultáneamente.\n• Recibir explicación clara de cualquier decisión de suspensión o desactivación.\n• Disputar cobros de membresía incorrectos dentro de los 30 días.\n• Acceder a tu historial de viajes y comprobantes de membresía a través de la app.\n• Terminar tu afiliación en cualquier momento contactando a soporte de V-Ride.\n\nOBLIGACIONES FISCALES\nEres responsable de declarar tus ingresos ante el SENIAT conforme a la legislación tributaria venezolana vigente. V-Ride no actúa como tu empleador a efectos fiscales ni retiene impuestos en tu nombre."},
    {"title":"Infracciones que Ponen en Riesgo tu Desactivación","body":"DESACTIVACIÓN PERMANENTE E INMEDIATA\n• Conducir bajo los efectos del alcohol o drogas (LTT 2008, Art. 169.8)\n• Negar el servicio a un pasajero con discapacidad protegido por la LOPCD\n• Conducta sexual inapropiada hacia un pasajero\n• Darse a la fuga en caso de accidente (LTT 2008, Art. 169.23)\n\nADVERTENCIA → SUSPENSIÓN → DESACTIVACIÓN\n• Uso del teléfono con las manos mientras conduces (LTT 2008, Art. 169.12)\n• Calificación sostenida por debajo de 4,5 estrellas\n\nSUSPENSIÓN INMEDIATA\n• Operar sin póliza de seguro de responsabilidad civil vigente (LTT 2008, Art. 170.3)\n• No pagar la membresía semanal dentro del plazo establecido (acceso bloqueado automáticamente)\n• No aprobar la verificación anual de antecedentes (suspensión pendiente de revisión)"}
  ]',
  updated_at = NOW()
WHERE code = 'VRN-TRN-025';

/* ═══════════════════════════════════════════════════════════════
   PREGUNTAS ADAPTADAS — MÓDULO 1
   Q5: membresía vence los viernes
   Q7: V-Ride cobra 0% de comisión por viaje
   ═══════════════════════════════════════════════════════════════ */
DELETE FROM training_questions
WHERE module_id = (SELECT id FROM training_modules WHERE code = 'VRN-TRN-021');

INSERT INTO training_questions (module_id, question_text, option_a, option_b, option_c, option_d, correct_option, order_index)
SELECT m.id, q.question_text, q.option_a, q.option_b, q.option_c, q.option_d, q.correct_option, q.order_index
FROM training_modules m,
(VALUES
  (1,  '¿Cuánto tiempo tienes para aceptar una solicitud de viaje?',
       '15 segundos', '30 segundos', '60 segundos', '2 minutos', 'B'),
  (2,  '¿Qué significa un indicador de estado verde en la app?',
       'Viaje en curso', 'La app necesita actualizarse', 'Estás conectado y disponible', 'Las ganancias están listas', 'C'),
  (3,  'Antes de iniciar un viaje, siempre debes:',
       'Preguntar al pasajero su destino', 'Confirmar el nombre del pasajero', 'Revisar el historial de viajes', 'Llamar al soporte de V-Ride', 'B'),
  (4,  '¿Dónde se encuentra el botón SOS durante un viaje activo?',
       'En la barra de navegación inferior', 'En la pestaña de Ganancias', 'En la esquina superior derecha de la pantalla', 'En la configuración de la cuenta', 'C'),
  (5,  '¿Cuándo vence el pago de la membresía semanal en V-Ride Venezuela?',
       'Los lunes', 'Los miércoles', 'Los viernes', 'Los domingos', 'C'),
  (6,  '¿Qué NUNCA debes compartir con los pasajeros?',
       'El modelo de tu vehículo', 'Tu nombre', 'Tu número de teléfono personal', 'Tu hora estimada de llegada', 'C'),
  (7,  '¿Cuánto cobra V-Ride Venezuela de comisión por cada viaje completado?',
       '13% de la tarifa', '20% de la tarifa', '10% de la tarifa', '0% — el conductor cobra el 100% directamente al pasajero', 'D'),
  (8,  'Si la navegación sugiere un desvío por tráfico, debes:',
       'Ignorarlo y tomar tu ruta preferida', 'Informar al pasajero antes de cambiar de ruta', 'Finalizar el viaje y pedir uno nuevo', 'Llamar primero a soporte', 'B'),
  (9,  '¿Cuánto tiempo debes esperar a un pasajero antes de marcarlo como ausente?',
       '2 minutos', '10 minutos', '5 minutos', '15 minutos', 'C'),
  (10, '¿A dónde vas en la app para registrar tu método de pago de membresía?',
       'Ayuda → Pagos', 'Cuenta → Configuración de Pagos', 'Ganancias → Configurar Cuenta', 'Inicio → Finanzas', 'B')
) AS q(order_index, question_text, option_a, option_b, option_c, option_d, correct_option)
WHERE m.code = 'VRN-TRN-021';

/* ═══════════════════════════════════════════════════════════════
   PREGUNTAS ADAPTADAS — MÓDULO 5
   Q3: seguro sin póliza → multa 5 U.T.
   Q7: comisión V-Ride = 0%
   Q9: obligación económica → membresía semanal
   ═══════════════════════════════════════════════════════════════ */
DELETE FROM training_questions
WHERE module_id = (SELECT id FROM training_modules WHERE code = 'VRN-TRN-025');

INSERT INTO training_questions (module_id, question_text, option_a, option_b, option_c, option_d, correct_option, order_index)
SELECT m.id, q.question_text, q.option_a, q.option_b, q.option_c, q.option_d, q.correct_option, q.order_index
FROM training_modules m,
(VALUES
  (1,  'El uso del teléfono con las manos mientras conduces está sancionado por la LTT 2008 y es motivo de desactivación en V-Ride. ¿Cuánto es la multa?',
       '3 U.T.', '5 U.T.', '10 U.T.', 'No hay multa si no hay accidente', 'C'),
  (2,  '¿Cuál es la edad mínima para conducir con V-Ride Venezuela?',
       '18 años (según la LTT 2008)', '21 años — V-Ride establece un estándar más alto', '25 años', '16 años con licencia de segundo grado', 'B'),
  (3,  'Según la LTT 2008, ¿qué consecuencia tiene circular sin póliza de seguro de responsabilidad civil vigente?',
       'No hay sanción si no ocurre ningún accidente', 'Solo se aplica sanción si hay víctimas', 'Multa de 5 U.T. y V-Ride suspende tu acceso a la plataforma', 'Suspensión automática de la licencia por 6 meses', 'C'),
  (4,  'Como contratista independiente, tus obligaciones fiscales en Venezuela son responsabilidad de:',
       'V-Ride, que paga los impuestos por ti', 'El SENIAT, sin que tengas que hacer nada', 'Ti mismo, ante el SENIAT', 'Nadie — los contratistas independientes están exentos', 'C'),
  (5,  '¿Qué debes hacer al pasar junto a un vehículo del INTT o PTT con luces encendidas?',
       'Ceder el paso a todos los peatones cercanos', 'Cambiarte de canal o reducir considerablemente la velocidad', 'Detenerte por completo siempre', 'Encender y apagar las luces altas', 'B'),
  (6,  '¿Cuál es la política de V-Ride Venezuela sobre conducir bajo los efectos del alcohol?',
       'Se permite hasta el límite legal establecido', 'No existe una política al respecto', 'Tolerancia cero — cualquier nivel detectado implica desactivación inmediata', 'Se permite un nivel bajo si el conductor se siente en condiciones', 'C'),
  (7,  '¿Qué porcentaje de la tarifa cobrada al pasajero retiene V-Ride como comisión por viaje?',
       '13%', '20%', '10%', '0% — el conductor cobra el 100% y paga una membresía semanal', 'D'),
  (8,  'Un conductor que recibe una denuncia de tolerancia cero debe:',
       'Ser suspendido de inmediato y reincorporado solo tras verificar resultado negativo', 'Recibir primero una advertencia escrita', 'Completar capacitación adicional antes de ser suspendido', 'Pagar una multa a la plataforma', 'A'),
  (9,  '¿Cuál es la principal obligación económica del conductor con V-Ride Venezuela?',
       'Pagar el 13% de cada tarifa como comisión mensual', 'Pagar una membresía semanal según el tipo de vehículo con el que opera', 'Pagar una cuota anual al inicio de cada año', 'No hay obligación — V-Ride descuenta su comisión automáticamente', 'B'),
  (10, 'Si la vía que tienes por delante está inundada, la normativa y la política de V-Ride establecen que:',
       'Puedes cruzar despacio si el agua parece poco profunda', 'Debes dar la vuelta — nunca conduzcas a través de agua de inundación', 'Esperas 30 minutos a que baje el agua', 'Llamas a V-Ride para recibir instrucciones antes de proceder', 'B')
) AS q(order_index, question_text, option_a, option_b, option_c, option_d, correct_option)
WHERE m.code = 'VRN-TRN-025';
